#!/usr/bin/env php
<?php

require_once get_cfg_var('goo.src_dir') . 'tools/vendor/illuminate/support/helpers.php';

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('DBDIFF_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

require DBDIFF_COMPOSER_INSTALL;


$dbdiff = new DBDiff\DBDiff;
$dbdiff->run();
